spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/chat?currentSchema=chat
      username: jhjeon
      password: 1234
chat:
  netty:
    websocket:
      enabled: true
      port: 8090
      path: /ws/chat
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-millis: 3600000
  permit-all-uris:
    - /api/v1/join
    - /api/v1/login
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs
    - /v3/api-docs/**
  authenticated-uris:
    - /api/v1/**
